import "@styles/globals.css";

import type { Metadata } from "next";
import { Toaster } from "@ui/sonner";
import { Inter } from "next/font/google";
import { ClerkProvider, QueryProvider, ThemeProvider } from "@providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
        <body className={inter.className}>
          <ThemeProvider>
            <QueryProvider>{children}</QueryProvider>

            <Toaster richColors position="bottom-center" />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
